language: node_js
node_js:
  - 'stable'
script:
  - npm test
  - cd ./frontEnd
  - npm install
  - npm run test-ci
  - npm run build-client-and-server
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: $heroku_api_key
    app: chris-vita-portfolio
    on:
      all_branches: true
    run:
      - restart